CREATE DATABASE db_lib;

USE db_lib;


CREATE TABLE PUBLISHER (
	Name VARCHAR(100) PRIMARY KEY NOT NULL,
	Address VARCHAR(100) NOT NULL,
	Phone VARCHAR(100) NOT NULL
	)
;

CREATE TABLE BORROWER (
	CardNo INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Name VARCHAR(100) NOT NULL,
	Address VARCHAR(100) NOT NULL,
	Phone VARCHAR(100) NOT NULL
	)
;

CREATE TABLE LIBRARY_BRANCH (
	BranchId INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	BranchName VARCHAR(100) NOT NULL,
	Address VARCHAR(100) NOT NULL
	)
;

CREATE TABLE BOOK (
	BookId INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	Title VARCHAR(100) NOT NULL,
	PublisherName VARCHAR(100) FOREIGN KEY REFERENCES PUBLISHER(Name) ON UPDATE CASCADE ON DELETE CASCADE
	)
;

CREATE TABLE BOOK_AUTHORS (
	AuthorId INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	BookId INT FOREIGN KEY REFERENCES BOOK(BookId) ON UPDATE CASCADE ON DELETE CASCADE,
	AuthorName VARCHAR(100) NOT NULL
	)
;

CREATE TABLE BOOK_LOANS (
	LoanId INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	BookId INT FOREIGN KEY REFERENCES BOOK(BookId) ON UPDATE CASCADE ON DELETE CASCADE,
	BranchId INT FOREIGN KEY REFERENCES LIBRARY_BRANCH(BranchId) ON UPDATE CASCADE ON DELETE CASCADE,
	CardNo INT FOREIGN KEY REFERENCES BORROWER(CardNo) ON UPDATE CASCADE ON DELETE CASCADE,
	DateOut DATE,
	DueDate DATE
	)
;

CREATE TABLE BOOK_COPIES (
	CopyId INT PRIMARY KEY NOT NULL IDENTITY(1,1),
	BookId INT FOREIGN KEY REFERENCES BOOK(BookId) ON UPDATE CASCADE ON DELETE CASCADE,
	BranchId INT FOREIGN KEY REFERENCES LIBRARY_BRANCH(BranchId) ON UPDATE CASCADE ON DELETE CASCADE,
	No_Of_Copies INT NOT NULL
	)
;



SELECT * FROM PUBLISHER;
SELECT * FROM BORROWER;
SELECT * FROM LIBRARY_BRANCH;
SELECT * FROM BOOK;
SELECT * FROM BOOK_AUTHORS;
SELECT * FROM BOOK_LOANS;
SELECT * FROM BOOK_COPIES;